export type Locale = "en" | "ar";

export const COPY = {
  en: {
    mark: "Keshf",
    kicker: "Statement atelier",
    headline: "Turn a bank export into a finished statement.",
    lede: "Drop an Excel or CSV file, choose the house template, and Keshf composes a typeset PDF — privately, in this browser.",
    banks: "House templates",
    dropTitle: "Statement file",
    dropHint: "xlsx, xls, or csv — the original export from the bank portal.",
    choose: "Choose file",
    sample: "Load sample ledger",
    convert: "Compose PDF",
    composing: "Composing",
    ready: "Statement ready",
    download: "Download PDF",
    another: "Start over",
    filename: "File name",
    rows: "transactions",
    empty: "No file yet",
    emptyHint: "A sample Riyadh-style ledger is one click away if you want to see the press at work.",
    errorTitle: "Could not finish",
    errorClose: "Close",
    parseFail: "This file could not be read as a statement.",
    missingFile: "Please choose a statement file first.",
    missingBank: "Please choose a bank template.",
    pdfFail: "The PDF press failed. The file may use an unexpected layout.",
    privacy: "Nothing leaves this device. Files are parsed in memory and discarded after download.",
    desktop: "Desktop source",
    lang: "العربية",
    metaCustomer: "Client",
    metaAccount: "Account",
    metaPeriod: "Period",
    colDate: "Date",
    colDetails: "Details",
    colDebit: "Debit",
    colCredit: "Credit",
    colBalance: "Balance",
    output: "Output",
    outputHint: "The browser will ask where to save. Rename below if you like.",
  },
  ar: {
    mark: "كشف",
    kicker: "أتيليه كشوف الحساب",
    headline: "حوّل تصدير البنك إلى كشف منسّق.",
    lede: "أفلت ملف إكسل أو CSV، اختر قالب المصرف، ويكشف يصفّ PDF بخط عربي — على هذا الجهاز فقط.",
    banks: "قوالب المصارف",
    dropTitle: "ملف الكشف",
    dropHint: "xlsx أو xls أو csv — التصدير الأصلي من بوابة البنك.",
    choose: "اختيار ملف",
    sample: "تحميل كشف تجريبي",
    convert: "تكوين PDF",
    composing: "جارٍ التكوين",
    ready: "الكشف جاهز",
    download: "تنزيل PDF",
    another: "البدء من جديد",
    filename: "اسم الملف",
    rows: "عملية",
    empty: "لا يوجد ملف بعد",
    emptyHint: "يوجد كشف تجريبي بأسلوب بنك الرياض بضغطة واحدة لمعاينة المطبعة.",
    errorTitle: "تعذّر الإتمام",
    errorClose: "إغلاق",
    parseFail: "تعذّرت قراءة هذا الملف ككشف حساب.",
    missingFile: "يرجى اختيار ملف الكشف أولاً.",
    missingBank: "يرجى اختيار قالب المصرف.",
    pdfFail: "فشلت المطبعة. قد يكون تخطيط الملف غير متوقع.",
    privacy: "لا يغادر شيء هذا الجهاز. تُقرأ الملفات في الذاكرة وتُهمل بعد التنزيل.",
    desktop: "نسخة سطح المكتب",
    lang: "English",
    metaCustomer: "العميل",
    metaAccount: "الحساب",
    metaPeriod: "الفترة",
    colDate: "التاريخ",
    colDetails: "التفاصيل",
    colDebit: "مدين",
    colCredit: "دائن",
    colBalance: "الرصيد",
    output: "المخرجات",
    outputHint: "سيطلب المتصفح مكان الحفظ. يمكن تعديل الاسم أدناه.",
  },
} as const;
